name: Intermediate environment variables
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      ACTOR: ${{ github.actor }} # コンテキストの値を環境変数へセット
    steps:
      - run: echo "${ACTOR}"     # 環境変数経由でコンテキストのプロパティを参照
      - uses: actions/checkout@v4
      - run: pwd
      - run: ls -ltr
      - run: pip install -r requirements.txt
      - run: pytest -s tests/