name: Secrets
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      PASS: ${{ secrets.PASSWORD }}
    steps:
      - run: echo "${PASS}"                   # ログ出力はマスクされる
      - run: echo "${PASS:0:1} ${PASS#?}" # ログ出力はマスクされない